# Generated by Django 3.0.7 on 2020-06-28 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counselor',
            name='is_counsel_gt_150',
        ),
        migrations.AddField(
            model_name='counselor',
            name='is_counsel_count_gt_150',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterModelTable(
            name='duration',
            table='duration',
        ),
    ]
